#!/bin/bash
if [ ! -f /home/gerrit2/review_site/hooks/error_log ]; then
    touch /home/gerrit2/review_site/hooks/error_log
fi
echo "$(date)" >> /home/gerrit2/review_site/hooks/error_log
echo "$@" >> /home/gerrit2/review_site/hooks/error_log
VAR="$(/usr/bin/python /home/gerrit2/review_site/hooks/webhook-process-hook --action comment "$@" 2>&1)"
echo ${VAR} >> /home/gerrit2/review_site/hooks/error_log
